version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5438'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
