version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  app_gateway:
    build: ./api-gateway/
    ports:
      - "3000:3333"
    env_file:
      - ./api-gateway/.env
    depends_on:
      db:
        condition: service_healthy

  exchange_rate:
    build: ./exchange-rate/
    env_file:
      - ./exchange-rate/.env
    depends_on:
      db:
        condition: service_healthy
  mailer:
    build: ./mailer/
    env_file:
      - ./mailer/.env
    depends_on:
      db:
        condition: service_healthy
  subscription:
    build: ./subscription/
    env_file:
      - ./subscription/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
